apiVersion: cicstx.ibm.com/v1
kind: CICSTXApplication
metadata:
  name: cicstx-ports-with-annotations
  annotations:
    imageregistry: "some registry"
spec:
  license: 'accept'
  replicas: 1
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/trial/adv:latest'
  imagePullPolicy: IfNotPresent
  #pullSecret: 'regrc'
  service:
    type: ClusterIP
    port: 1435
    portName: cicstx
    ports:
      - name : metrics
        port : 9087
        targetPort: 80
        #nodePort: 32062
  createAppDefinition: true
  monitoring:
    labels :
      env: production
    endpoints:
    - port: metrics
  volumeMounts:
  - mountPath: /cache
    name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  storage:
    size : 1Gi
    storageClassName: nfs-storage-provisioner

